services:
  - type: web
    name: video-recommendation-engine
    env: python
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
